version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: web.docker
    volumes:
      - ./:/var/www/
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3507:80"
    links:
      - app
    restart: always
  app:
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ./:/var/www/
      - ./php.ini:/usr/local/etc/php/php.ini
    restart: always
networks:
  default:
    external:
      name: urcomx_net
